pipeline {
    agent {
        docker {
                image 'maven:3-alpine'
                customWorkspace './cloud-parent/cloud-eureka-server/'
                }
           }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
                sh 'mvn clean package'
            }
        }
    }
}