pipeline {
    agent { docker 'maven:3.3.3'
            customWorkspace ./cloud-parent/cloud-eureka-server}
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
                sh 'mvn clean package'
            }
        }
    }
}