pipeline {
	agent none
	stages {
		stage('Package') {
			agent {
				docker {
					image 'maven:3-alpine'
					args '-v /usr/share/maven/ref:/root/.m2 -v /home/docker/mavensettings/settings-bigdata.xml:/usr/share/maven/conf/settings.xml'
				}
			}
			steps {
				sh 'mvn --version'
				sh 'cd cloud-parent && mvn clean package -Dmaven.test.skip=true'
			}
		}

		stage('feign') {
			agent any
			steps {
				sh 'cd cloud-parent/cloud-feign && mv target/cloud-feign-0.0.1-SNAPSHOT.jar docker/cloud-feign.jar && docker build -t cloud-feign-$BRANCH_NAME docker/'
			}
		}

		stage('ribbon') {
			agent any
			steps {
				sh 'cd cloud-parent/cloud-ribbon && mv target/cloud-ribbon-0.0.1-SNAPSHOT.jar docker/cloud-ribbon.jar && docker build -t cloud-ribbon-$BRANCH_NAME docker/'
			}
		}
		stage('zuul') {
			agent any
			steps {
				sh 'cd cloud-parent/cloud-zuul && mv target/cloud-zuul-0.0.1-SNAPSHOT.jar docker/cloud-zuul.jar && docker build -t cloud-zuul-$BRANCH_NAME docker/'
			}
		}
	}
}