pipeline {
	agent none
	stages {
		stage('Package') {
			agent {
				docker {
					image 'maven:3-alpine'
					args '-v /root/.m2:/root/.m2 -v /root/.m2/settings.xml:/usr/share/maven/conf/settings.xml'
				}
			}
			steps {
				sh 'mvn --version'
				sh 'cd cloud-parent && mvn clean package -Dmaven.test.skip=true'
			}
		}

		stage('eureka-server') {
			agent any
			steps {
				sh 'cd cloud-parent/cloud-eureka-server && mv target/cloud-eureka-server-0.0.1-SNAPSHOT.jar docker/cloud-eureka-server.jar && docker build -t cloud-eureka-server docker/'
			}
		}

		stage('feign') {
			agent any
			steps {
				sh 'cd cloud-parent/cloud-feign && mv target/cloud-feign-0.0.1-SNAPSHOT.jar docker/cloud-feign.jar && docker build -t cloud-feign docker/'
			}
		}
		stage('config-server') {
			agent any
			steps {
				sh 'cd cloud-parent/cloud-config-server && mv target/cloud-config-server-0.0.1-SNAPSHOT.jar docker/cloud-config-server.jar && docker build -t cloud-config-server docker/'
			}
		}

		stage('ribbon') {
			agent any
			steps {
				sh 'cd cloud-parent/cloud-ribbon && mv target/cloud-ribbon-0.0.1-SNAPSHOT.jar docker/cloud-ribbon.jar && docker build -t cloud-ribbon docker/'
			}
		}
		stage('zuul') {
			agent any
			steps {
				sh 'cd cloud-parent/cloud-zuul && mv target/cloud-zuul-0.0.1-SNAPSHOT.jar docker/cloud-zuul.jar && docker build -t cloud-zuul docker/'
			}
		}


		stage('Run Eureka Server') {
			agent any
			options {
				retry(3)
			}
			steps {
				sh 'docker run -d --rm -p 8761:8761 cloud-eureka-server'
			}
		}
		stage('Run Config Server') {
			agent any
			options {
				retry(3)
			}
			steps {
				sh 'docker run -d --rm  -p 8088:8088 cloud-config-server'
			}
		}
		stage('Run Feign') {
			agent any
			options {
				retry(3)
			}
			steps {
				sh 'docker run -d --rm  -p 8762:8762  cloud-feign'
			}
		}
		stage('Run Ribbon Server') {
			agent any
			options {
				retry(3)
			}
			steps {
				sh 'docker run -d --rm -p 8763:8763  cloud-ribbon'
			}
		}
		stage('Run Zuul Server') {
			agent any
			options {
				retry(3)
			}
			steps {
				sh 'docker run -d --rm -p 8764:8764  cloud-zuul'
			}
		}
	}
}