pipeline {
	agent none
	stages {
		stage('build') {
			agent {
				docker {
					image 'maven:3-alpine'
					args '-v /root/.m2:/root/.m2 -v /root/.m2/settings.xml:/usr/share/maven/conf/settings.xml'
				}
			}
			steps {
				sh 'mvn --version'
				sh 'cd cloud-parent && mvn clean package -Dmaven.test.skip=true'
			}
		}
	}
}