eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: 163                     #网关路由到网易官网
          uri: http://www.163.com/
          predicates:
              - Path=/163/**
        - id: feign                     #网关路由到网易官网
          uri: lb://SERVICE-FEIGN
          filters:
              - StripPrefix=1
          predicates:
            - Path=/feign/**
        - id: ribbon                     #网关路由到网易官网
          uri: lb://SERVICE-RIBBON
          filters:
              - StripPrefix=1
          predicates:
              - Path=/ribbon/**