eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.159:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: 163                     #网关路由到网易官网
          uri: http://www.163.com/
          predicates:
              - Path=/163/**
#        - id: api-a
#          uri: lb://SERVICE-RIBBON
#          predicates:
#            - Path=/API-RIBBON
#        - id: api-b
#          uri: lb://SERVICE-FEIGN
#          predicates:
#            - Path=/API-FEIGN